### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by insung151** [swsnu/swpp18-team12#13]
- [x] model_test @hojunroks 
- [x] club_detail_front @snumath 
- [x] club_detail_back @hojunroks 
- [x] user_rating_front @snumath 
- [x] user_rating_back @insung151 
- [x] search_back @insung151 
- [x] main_back @insung151 
- [x] report @hojunroks 
- [x] qa @insung151 
- [x] event, promotion post @insung151
