### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by snumath** [swsnu/swpp18-team12#26]
- [ ] CKEditor (프론트, 백 둘다)
- [ ] nginx deploy (이영재), 늦어도 금요일까지
- [ ] Design 갈아엎기 (12월 15일) 
---
- [ ] Accout 관리 페이지 (/change_password -> /account/change_password)
- [ ] Event REST (article, comment)
  article은 ckeditor, comment는 plain text
- [ ] 사진 건내주고 받기
- [ ] nginx 끝나면 8000번 경유하는 링크를 프론트에 통합
- [ ] main 추가
- [ ] Search result 개수 문제 => DB 초기화하면 해결되는 것으로 판명!
---
- [ ] search
- [ ] DB 한번 더 갈아엎기
